### ISSUE TITLE
Assign IDs to annotations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/iiif-annotations#3]
Annotations are published as an array of `items` inside each `AnnotationPage`, but don't have annotation IDs at the moment.

>Annotations must have their own HTTP(S) URIs, conveyed in the id property. The JSON-LD description of the Annotation should be returned if the URI is dereferenced, according to the [Web Annotation Protocol](http://w3.org/TR/annotation-protocol/).

https://iiif.io/api/presentation/3.0/#56-annotation

**Comment by glenrobson** [comment]
It looks like Annotation Ids are important to get them to work correctly in Mirador. See this demo:

https://glenrobson.github.io/iiif_stuff/zooniverse/with_id/

compared with annotations without ids:

https://glenrobson.github.io/iiif_stuff/zooniverse/split/

**Comment by eatyourgreens** [comment]
Thanks Glen. I’ll add IDs to the annotations tomorrow. It’s exciting to see the Zooniverse and BL data side-by-side in Mirador.

**Comment by snblickhan** [comment]
This is really cool to see, thanks Glen!

**Comment by eatyourgreens** [comment]
I've assigned IDs based on the project slug and item index, which should work for workflows that only have one annotation task. These should get the annotations working in Mirador.
- https://zooniverse.github.io/iiif-annotations/bldigital/in-the-spotlight/dates/0
- https://zooniverse.github.io/iiif-annotations/bldigital/in-the-spotlight/titles/0
