### ISSUE TITLE
Split annotations by canvas

### ISSUE THREAD

**Issue by glenrobson** [zooniverse/iiif-annotations#4]
The traditional way of doing annotations in IIIF is to have an AnnotationPage per Canvas. It looks like the annotations here:

https://zooniverse.github.io/iiif-annotations/annotations/titles/0.json

are for all canvases. I think it would be better to have an `annotationPage` per canvas and an `annotationCollection` per Manifest. 

Having all of the annotations in one `annotationPage` looks like this:

https://glenrobson.github.io/iiif_stuff/zooniverse/original/

(all of the annotations are shown for the canvas that  has the linked `annotationPage`)

as opposed to this example which only has the annotations for the canvas you are viewing:

https://glenrobson.github.io/iiif_stuff/zooniverse/with_id/

**Comment by eatyourgreens** [comment]
Thanks Glen. This is done now, so each of the annotation collections should  link to 447 annotation pages, one per canvas. Annotations are concentrated towards the beginning of the set, so the later annotation pages are mostly empty.
