### ISSUE TITLE
Optional: include link to manifest in the annotation

### ISSUE THREAD

**Issue by glenrobson** [zooniverse/iiif-annotations#5]
Its possible to include a link to the manifest in the annotation. This is helpful when processing the annotation page as it is the only way to get to the source image (as the canvas ID isn't resolvable). 

I've created a test example here:

https://glenrobson.github.io/iiif_stuff/zooniverse/partof/

It does work in Mirador 3 and I was hoping it would also work in another IIIF tool called [Annona](https://ncsu-libraries.github.io/annona/) but unfortunately it doesn't look like it does. 

I would recommend including this if you can, as its useful to keep the connection between the annotationPage and the manifest but it won't make any difference to the viewing experience if the Manifest points to the annotationPage so I think its a if you've got time thing.

**Comment by glenrobson** [comment]
I've reported the issue with Annona here: https://github.com/NCSU-Libraries/annona/issues/35 and it could well be that I'm not structuring the annotation correctly.

**Comment by eatyourgreens** [comment]
That looks straightforward. It should be a case of replacing the targets here:
https://github.com/zooniverse/iiif-annotations/blob/87b4d64fb90fcff2899c220db33e3b7d59a5f098/annotations/titles/titles.11tydata.js#L26

And here:
https://github.com/zooniverse/iiif-annotations/blob/87b4d64fb90fcff2899c220db33e3b7d59a5f098/annotations/dates/dates.11tydata.js#L12

**Comment by eatyourgreens** [comment]
I've updated the annotation targets to include `partOf`. We can iterate on this if it turns out that the British Library can't use these targets. It sounds promising that it works in Mirador!

**Comment by glenrobson** [comment]
I've just been testing the latest output you've generated and unfortunately its not working with Mirador:

https://glenrobson.github.io/iiif_stuff/zooniverse/Mar_2022/

Comparing your [annotation page](https://zooniverse.github.io/iiif-annotations/annotations/titles/0.json) with the one [I generated](https://glenrobson.github.io/iiif_stuff/zooniverse/partof/annoPage-0.json) the only difference I can see is you are missing `"type": "SpecificResource"` in the annotation target. So it should look like:

```
target": {
    "type": "SpecificResource",
    "source": {
        "id": https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589176.0x0001c3",
        "type": "Canvas",
        "partOf": [
            {
                "id": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589176.0x000002/manifest.json",
                "type": "Manifest"
            }
        ]
    },
    "selector": {
        "type": "FragmentSelector",
        "conformsTo": "http://www.w3.org/TR/media-frags/",
        "value": "xywh=570,1472,1814,314"
    }
},
```

Also Niqui has fixed the issue I raised with Annona so that does now work on the link I put above.

**Comment by eatyourgreens** [comment]
Thanks! I'll fix that.

**Comment by eatyourgreens** [comment]
@glenrobson those types should be present on the annotation targets now. GH Pages just finished publishing the new files, but I'm not sure how long the old ones might be cached.
